### ISSUE TITLE
jsonではなくyamlを使うべきでは

### ISSUE THREAD

**Issue by sirotama** [GoWorldGame/GoWorldGame-DesignNote#1]
ゲームのような通信量の多いアプリケーションにおいてjsonを使うべきではないのではというように思うが

**Comment by xReiju** [comment]
あとでREADMEに書き足すけど
これは大きな要素として

* マップ
* 戦闘

で分かれている
基本的に、クライアントサイドでゲームは進み、モンスターの育成等も行われていく
誰かと戦闘するときに、相手のモンスターのHPなどを初期化処理用にサーバーへ送る
その情報は自分と相手の双方に送信され、クライアント側で描写等の準備をする
そして、モンスターが技を出すときにクライアントから出した技をサーバーに送信する
両方共送信したらサーバー側で命中したか等の結果を処理、クライアントに結果を送信

てな感じ　説明不足ですまん

**Comment by xReiju** [comment]
いわゆるターン制

**Comment by sirotama** [comment]
ふむ

**Comment by xReiju** [comment]
ポ●ケモンを想像してくれ

**Comment by sirotama** [comment]
なるほど

**Comment by xReiju** [comment]
あーでもYAMLいいかもな

**Comment by xReiju** [comment]
http://ryoff.hatenablog.com/entry/20090920/1253467118
小さいファイルの場合、JSONが向いているようなのでJSONにします。
